name: Vault OIDC Test

on:
  workflow_dispatch:  # Можна запустити вручну
  push:
    branches: [ main ]

jobs:
  vault-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Важливо для OIDC
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Vault
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault
      
      - name: Authenticate to Vault via OIDC
        env:
          VAULT_ADDR: "https://vault-cluster-public-vault-b32ba3e5.34198e2e.z1.hashicorp.cloud:8200"
          VAULT_NAMESPACE: "admin"
        run: |
          # Отримати JWT токен від GitHub з правильним audience
          GITHUB_JWT=$(curl -sLS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/Mayored" | jq -r '.value')
          echo "JWT токен отримано"
          
          # Автентифікуватись у Vault з роллю github-readonly
          VAULT_TOKEN=$(vault write -field=token auth/jwt/login role=github-readonly jwt=$GITHUB_JWT)
          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
          echo "✅ Успішна автентифікація у Vault!"
          
      - name: Read secret from Vault
        run: |
          export VAULT_ADDR="https://vault-cluster-public-vault-b32ba3e5.34198e2e.z1.hashicorp.cloud:8200"
          export VAULT_NAMESPACE="admin"
          vault kv get myapp/auth
